export const BEAP_SCALES = {
  dog: [
    { key: "breathing", letter: "B", label: "Breathing", levels: [
      "Calm, normal breathing.",
      "Normal breathing, occasional panting.",
      "A little faster or heavier breathing.",
      "Noticeably faster, more effort to breathe.",
      "Rapid, laboured breathing, even at rest.",
      "Distressed, gasping, or open-mouth breathing.",
    ] },
    { key: "eyes", letter: "E", label: "Eyes / Face", levels: [
      "Ears relaxed, eyes bright, smooth brow, relaxed muzzle.",
      "Ears slightly back, mild squint, a little brow tension.",
      "Ears pulled back, squinting, furrowed brow.",
      "Ears flattened, eyes dull or half-closed, worried look.",
      "Ears pinned, eyes wide or squeezed shut, panicked look.",
      "Vacant stare or unresponsive, ears pinned flat.",
    ] },
    { key: "ambulation", letter: "A", label: "Ambulation (walking & stairs)", levels: [
      "Walks normally, manages stairs easily.",
      "Occasional stiffness, otherwise normal.",
      "Mild limping or hesitant on stairs.",
      "Noticeable limping, avoids stairs.",
      "Reluctant to bear weight, won't attempt stairs.",
      "Unable or unwilling to walk.",
    ] },
    { key: "activity", letter: "A", label: "Activity", levels: [
      "Plays and engages in all normal activities.",
      "Slightly less playful than usual.",
      "Reduced interest in play or activity.",
      "Mostly rests, withdrawn from family.",
      "Reluctant to move; licking or chewing a painful area, or accidents in the house.",
      "Won't get up at all; incontinence.",
    ] },
    { key: "appetite", letter: "A", label: "Appetite", levels: [
      "Eating and drinking normally.",
      "Slightly slower to eat.",
      "A bit picky, some hesitancy.",
      "Eating noticeably less; only wants treats or human food.",
      "Little interest in food or water, even treats.",
      "Refusing food and water.",
    ] },
    { key: "attitude", letter: "A", label: "Attitude", levels: [
      "Happy, interested, seeks attention.",
      "Generally happy, occasionally withdrawn.",
      "Somewhat subdued or less interested.",
      "Withdrawn, less interested in family.",
      "Avoids interaction, anxious or irritable.",
      "Unresponsive or clearly distressed.",
    ] },
    { key: "posture", letter: "P", label: "Posture", levels: [
      "Relaxed at rest and during play; tail moving normally.",
      "Mostly relaxed; tail a little lower or flickier.",
      "Slightly tense or restless; tail lower or flicking more.",
      "Tense, guarded, reluctant to lie down; tail tucked.",
      "Hunched, tucked tail, odd position.",
      "Rigid, trembling, can't get comfortable.",
    ] },
    { key: "palpation", letter: "P", label: "Palpation (response to touch)", levels: [
      "Enjoys touch, no tension.",
      "Comfortable, mild tension in one area.",
      "Some sensitivity or mild flinching.",
      "Flinches or pulls away from a specific area.",
      "Guards or growls when touched.",
      "Won't tolerate touch, cries out or snaps.",
    ] },
  ],
  cat: [
    { key: "breathing", letter: "B", label: "Breathing", levels: [
      "Calm, normal breathing.",
      "Normal breathing, occasionally a little quicker.",
      "A little faster or heavier breathing.",
      "Noticeably faster, more effort to breathe.",
      "Rapid, laboured, open-mouth breathing. (emergency)",
      "Distressed, gasping, or extreme effort to breathe. (emergency)",
    ] },
    { key: "eyes", letter: "E", label: "Eyes / Face", levels: [
      "Ears forward, eyes round with normal pupils, relaxed muzzle, whiskers loose.",
      "Ears slightly rotated, mild squint, pupils a touch wider.",
      "Ears rotated out or back, moderate squint, dilated pupils.",
      "Ears flattened, squinting with a tense muzzle (grimace face), whiskers bunched.",
      "Ears tightly flattened, eyes tightly closed, clear grimace face.",
      "Vacant stare or unresponsive, ears pinned flat, pupils fixed.",
    ] },
    { key: "ambulation", letter: "A", label: "Ambulation (jumping, walking & stairs)", levels: [
      "Jumps and walks normally, manages stairs easily.",
      "Occasional hesitation before jumping or using stairs.",
      "Mild reluctance to jump or use stairs.",
      "Avoids jumping and stairs, some limping.",
      "Won't jump or use stairs, noticeable limping.",
      "Unable or unwilling to walk or jump.",
    ] },
    { key: "activity", letter: "A", label: "Activity", levels: [
      "Normal play, exploring, and grooming.",
      "Slightly less playful than usual.",
      "Reduced play, grooms a little less.",
      "Mostly rests, withdrawn from family.",
      "Hiding more; licking or chewing a painful area, or accidents outside the litter tray.",
      "Withdrawn and hiding, won't engage; incontinence.",
    ] },
    { key: "appetite", letter: "A", label: "Appetite", levels: [
      "Eating and drinking normally.",
      "Slightly slower to eat.",
      "A bit picky, some hesitancy.",
      "Eating noticeably less; only wants treats or human food.",
      "Little interest in food or water, even treats — in cats this needs prompt attention.",
      "Refusing food and water.",
    ] },
    { key: "attitude", letter: "A", label: "Attitude", levels: [
      "Sociable, curious, seeks attention.",
      "Generally sociable, occasionally withdrawn.",
      "Somewhat subdued or less interested.",
      "Withdrawn, hides more, less interested in family.",
      "Avoids interaction, anxious or irritable.",
      "Unresponsive or clearly distressed.",
    ] },
    { key: "posture", letter: "P", label: "Posture", levels: [
      "Relaxed at rest; tail moving normally.",
      "Mostly relaxed; tail a little lower or twitchier.",
      "Sits hunched or tense ('loaf') more than usual; tail flicking more.",
      "Hunched 'loaf' posture for long periods; tail low or tucked.",
      "Tightly hunched, tucked in, won't move from position.",
      "Rigid, trembling, can't get comfortable.",
    ] },
    { key: "palpation", letter: "P", label: "Palpation (response to touch)", levels: [
      "Enjoys touch, no tension.",
      "Comfortable, mild tension in one area.",
      "Some sensitivity or mild flinching.",
      "Flinches or pulls away from a specific area.",
      "Guards, hisses, or growls when touched.",
      "Won't tolerate touch, hisses, cries out, or swats.",
    ] },
  ],
};
